version: '3'

services:
  snippets:
    container_name: "infra-snippets-api"
    image: ghcr.io/ingsis-jcli/snippets:latest
    environment:
      GITHUB_ACTOR: "${GITHUB_ACTOR}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${S_POSTGRES_DB}"
      POSTGRES_HOST: "${S_POSTGRES_HOST}"
      PORT: "${PORT}"
    ports:
      - "${S_PORT}:${PORT}"
    depends_on:
      - db-snippets
      - redis
    restart: unless-stopped

  db-snippets:
    container_name: "${S_POSTGRES_HOST}"
    image: postgres:15
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${S_POSTGRES_DB}"
    ports:
      - "${S_POSTGRES_PORT}:5432"
    restart: unless-stopped


  permissions:
    container_name: "infra-permissions-api"
    image: ghcr.io/ingsis-jcli/permissions:latest
    environment:
      GITHUB_ACTOR: "${GITHUB_ACTOR}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${P_POSTGRES_DB}"
      POSTGRES_HOST: "${P_POSTGRES_HOST}"
      PORT: "${PORT}"
    ports:
      - "${P_PORT}:${PORT}"
    depends_on:
      - db-permissions
    restart: unless-stopped

  db-permissions:
    container_name: "${P_POSTGRES_HOST}"
    image: postgres:15
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${P_POSTGRES_DB}"
    ports:
      - "${P_POSTGRES_PORT}:5432"
    restart: unless-stopped

  printscript:
    platform: linux/x86_64
    container_name: "infra-printscript-api"
    image: ghcr.io/ingsis-jcli/printscript:latest
    environment:
      GITHUB_ACTOR: "${GITHUB_ACTOR}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      PORT: "${PORT}"
      AUTH0_AUDIENCE: "${AUTH0_AUDIENCE}"
      AUTH_SERVER_URI: "${AUTH_SERVER_URI}"
      AUTH_CLIENT_ID: "${AUTH_CLIENT_ID}"
      AUTH_CLIENT_SECRET: "${AUTH_CLIENT_SECRET}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PORT: "${REDIS_PORT}"
    ports:
      - "${PS_PORT}:${PORT}"
    depends_on:
      - redis
    restart: unless-stopped

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: unless-stopped
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  asset-api:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "${BUCKET_PORT}:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: "true"
    restart: unless-stopped

  redis:
    container_name: "redis"
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  ui-service:
    platform: linux/x86_64
    container_name: "infra-ui"
    image: ghcr.io/ingsis-jcli/snippet-ui:latest
    ports:
      - "3000:80"
    restart: unless-stopped

  nginx:
    container_name: "reverse-proxy"
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static/:/usr/share/nginx/html:ro
      - /etc/letsencrypt/live/jcli-snippetsearcher.duckdns.org:/etc/letsencrypt/live/jcli-snippetsearcher.duckdns.org:ro
      - /etc/letsencrypt/archive/jcli-snippetsearcher.duckdns.org:/etc/letsencrypt/archive/jcli-snippetsearcher.duckdns.org:ro
    depends_on:
      - ui-service
      - snippets
      - permissions
      - printscript
    restart: unless-stopped

  newrelic-agent:
    container_name: newrelic-infra
    build:
      context: .
      dockerfile: newrelic-infra.dockerfile
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - SUBDOMAINS=${DUCK_SUBDOMAIN}
      - TOKEN=${DUCK_TOKEN}
    restart: unless-stopped

volumes:
  blob:
    external: false
