name: "Continuous Deployment"

on:
  push:
    branches:
      - dev

jobs:
  deploy_to_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Update service on VM with new image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST_DEV }}
          username: ${{ secrets.VM_USER_DEV }}
          key: ${{ secrets.VM_KEY_DEV }}
          script: |
            pwd
            cd infra
            git pull origin dev
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login -u ${{ github.actor }} --password-stdin ghcr.io
            sudo docker-compose -f docker-compose.dev.yml down
            sudo docker-compose -f docker-compose.dev.yml pull
            sudo docker-compose -f docker-compose.dev.yml up -d